### ISSUE TITLE
vboxheadless on container gives -> Error -1909 in suplibOsInit!,  Kernel driver not accessible

### ISSUE THREAD

**Issue by tomekit** [Jencryzthers/VboxInsideDocker#10]
Hi,
Thanks for sharing your work. I've thought you would be able to help me out with trying to run VBox inside of Docker container.

I am getting:
```
root@089e849c5097:/# vboxheadless 
VBoxHeadless: Error -1909 in suplibOsInit!
VBoxHeadless: Kernel driver not accessible
VBoxHeadless: Tip! Make sure the kernel module is loaded. It may also help to reinstall VirtualBox.
```
from inside my container.

I am running Ubuntu 16.04 host, with virtualbox installed.
`vboxheadless -V` gives `5.2.8r121009`.

`sudo /etc/init.d/virtualbox status` gives `Active: active`

I've run the container using this command: `docker run -d -v /dev/vboxdrv:/dev/vboxdrv --name=vbox jencryzthers/vboxinsidedocker`.

Unfortunately I can't run Virtualbox inside. 

I would appreciate if you could send me some hints. Thanks !

**Comment by ghost** [comment]
did you find a solution ?
